### PR TITLE
Fixes issue #43

### PR DESCRIPTION
**Pull request by LilCrispy2o9**

### CODE REVIEW

**Comment by Tethered** [comment]
What is VARCHAR?

**Comment by LilCrispy2o9** [comment]
Holds letters and numbers

**Comment by Tethered** [comment]
Does TEXT not do that, or is TEXT just letters? And what if the world name has weird characters in it?

**Comment by LilCrispy2o9** [comment]
TEXT is just letters i believe. Define weird characters?

**Comment by Tethered** [comment]
(*&&%$^$)(}{][| pretty much anything that isnt alphanumeric or a number. I don't even know if worlds are allowed to be named this way...

**Comment by LilCrispy2o9** [comment]
I dont think so, and I dont see why someone would.

**Comment by Tethered** [comment]
I used your bugfixes in the latest commit, but couldn't add them previously because i had merged an earlier commit. I still gave you credit though!

**Pull request closed without merging**
